<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UserSeeder extends Seeder
{
    public function run()
    {
        $data = [
            [
                'name' => 'Lisa Brown',
                'email' => 'lisa.brown@example.com',
                'usertype' => 'user',
                'password' => bcrypt('password123'),
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'about' => 'Alumni Sistem Informasi yang aktif dalam pengembangan data.',
                'contact' => '6281212341234',
                'job' => 'Data Analis',
                'photo' => null,
                'status' => 'active',
                'birth_of_date' => '1991-06-15',
                'remember_token' => null,
                'current_team_id' => null,
                'profile_photo_path' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'program_studi' => 'Sistem Informasi',
                'angkatan' => '2004',
                'tempatKerja' => 'Agoda',
            ],
            [
                'name' => 'John Doe',
                'email' => 'john.doe@example.com',
                'usertype' => 'user',
                'password' => bcrypt('password123'),
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'about' => 'Programmer dengan pengalaman luas.',
                'contact' => '6281112345678',
                'job' => 'Programmer',
                'photo' => null,
                'status' => 'active',
                'birth_of_date' => '1990-05-20',
                'remember_token' => null,
                'current_team_id' => null,
                'profile_photo_path' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'program_studi' => 'Informatika',
                'angkatan' => '2006',
                'tempatKerja' => 'Google',
            ],
            [
                'name' => 'Michael White',
                'email' => 'michael.white@example.com',
                'usertype' => 'user',
                'password' => bcrypt('password123'),
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'about' => 'Teknisi jaringan yang handal.',
                'contact' => '6281987654321',
                'job' => 'Teknisi Jaringan',
                'photo' => null,
                'status' => 'active',
                'birth_of_date' => '1992-10-10',
                'remember_token' => null,
                'current_team_id' => null,
                'profile_photo_path' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'program_studi' => 'Teknik Elektro',
                'angkatan' => '2010',
                'tempatKerja' => 'Facebook',
            ],
            [
                'name' => 'Jane Smith',
                'email' => 'jane.smith@example.com',
                'usertype' => 'user',
                'password' => bcrypt('password123'),
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'about' => 'Perancang UI/UX profesional.',
                'contact' => '6281998765432',
                'job' => 'Perancang UI/UX',
                'photo' => null,
                'status' => 'active',
                'birth_of_date' => '1988-04-25',
                'remember_token' => null,
                'current_team_id' => null,
                'profile_photo_path' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'program_studi' => 'Teknologi Informasi',
                'angkatan' => '2005',
                'tempatKerja' => 'Apple',
            ],
            [
                'name' => 'Sarah Connor',
                'email' => 'sarah.connor@example.com',
                'usertype' => 'user',
                'password' => bcrypt('password123'),
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'about' => 'Data Analyst dengan pengalaman luas.',
                'contact' => '6281234567890',
                'job' => 'Data Analis',
                'photo' => null,
                'status' => 'active',
                'birth_of_date' => '1995-12-10',
                'remember_token' => null,
                'current_team_id' => null,
                'profile_photo_path' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'program_studi' => 'Manajemen Rekayasa',
                'angkatan' => '2013',
                'tempatKerja' => 'Amazon',
            ],
            [
                'name' => 'Emily Davis',
                'email' => 'emily.davis@example.com',
                'usertype' => 'user',
                'password' => bcrypt('password123'),
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'about' => 'Ahli Teknologi Informasi dengan keahlian di bidang software.',
                'contact' => '6281223456789',
                'job' => 'Programmer',
                'photo' => null,
                'status' => 'active',
                'birth_of_date' => '1987-07-07',
                'remember_token' => null,
                'current_team_id' => null,
                'profile_photo_path' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'program_studi' => 'Teknik Komputer',
                'angkatan' => '2012',
                'tempatKerja' => 'IBM',
            ],
            [
                'name' => 'Daniel Carter',
                'email' => 'daniel.carter@example.com',
                'usertype' => 'user',
                'password' => bcrypt('password123'),
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'about' => 'Mahasiswa aktif yang mengejar karir di bidang Bioproses.',
                'contact' => '6281996543210',
                'job' => 'Teknisi Jaringan',
                'photo' => null,
                'status' => 'active',
                'birth_of_date' => '1996-11-11',
                'remember_token' => null,
                'current_team_id' => null,
                'profile_photo_path' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'program_studi' => 'Bioproses',
                'angkatan' => '2015',
                'tempatKerja' => 'Tesla',
            ],
            [
                'name' => 'Olivia Brown',
                'email' => 'olivia.brown@example.com',
                'usertype' => 'user',
                'password' => bcrypt('password123'),
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'about' => 'Pengembang aplikasi di perusahaan terkemuka.',
                'contact' => '6281776543210',
                'job' => 'Sistem Analis',
                'photo' => null,
                'status' => 'active',
                'birth_of_date' => '1994-02-14',
                'remember_token' => null,
                'current_team_id' => null,
                'profile_photo_path' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'program_studi' => 'TRPL',
                'angkatan' => '2018',
                'tempatKerja' => 'Microsoft',
            ],
        ];

        foreach ($data as $item) {
            DB::table('users')->insert($item);
        }
    }
}
